export interface Song {
  id: string;
  title: string;
  artist: string;
  album: string;
  coverUrl: string;
  audioUrl?: string; // Optional for demo purposes
  lyricsUrl?: string;
  addedAt: number;
  description?: string; // Generated by Gemini
}

export interface PlayerState {
  currentSong: Song | null;
  isPlaying: boolean;
  volume: number;
  progress: number; // 0-100
  duration: number; // in seconds
}

export enum View {
  RECENTLY_ADDED = 'RECENTLY_ADDED',
  ARTISTS = 'ARTISTS',
  ALBUMS = 'ALBUMS',
  SONGS = 'SONGS',
  LIKED = 'LIKED'
}